### DISCUSSION TITLE
Unable to get nonce loop on a new server

### DISCUSSION THREAD

**Discussion by gobnat** [nginx-proxy/acme-companion#1023] [Q&A]
Hello,

I've been using `nginx-proxy` and `acme-companion` on a django/vue project for the last year without issue. I have been running my containers on an ubuntu 20 system. 

As part of upgrading I have created a new server running ubuntu 22 and the latest version of docker (23.0.3)

my docker compose for nginx looks like the following:

```yaml
version: "3.9"
services:
  backend:
    container_name: backend
   ...
    environment:
      - VIRTUAL_HOST=stage.admin.mysite.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=stage.admin.mysite.com
   ...

  frontend:
    container_name: frontend
    ...
    environment:
      - VIRTUAL_HOST=stage.mysite.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=stage.mysite.com
    expose:
      - 8080
     
  
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    env_file:
      - ./env/.env.proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #network_mode: bridge
    depends_on:
      - nginx-proxy
```

The only thing I have changed from the working system is adding the sub-domain "stage" to the HOST urls. 

While docker compose builds and starts without error the sites are not accessible and the following error is output:

```
nginx-proxy-acme  | [Mon Apr 10 05:17:57 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28

nginx-proxy-acme  | [Mon Apr 10 05:17:57 UTC 2023] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.

nginx-proxy-acme  | [Mon Apr 10 05:17:57 UTC 2023] Registering account: https://acme-v02.api.letsencrypt.org/directory

nginx-proxy-acme  | [Mon Apr 10 05:20:08 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28

nginx-proxy-acme  | [Mon Apr 10 05:20:08 UTC 2023] Could not get nonce, let's try again.

nginx-proxy-acme  | [Mon Apr 10 05:22:22 UTC 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28

nginx-proxy-acme  | [Mon Apr 10 05:22:22 UTC 2023] Could not get nonce, let's try again.
```

and keeps looping. 

I assume it is a server configuration issue but so far the following seems to all be ok:

1. ufw is active and allowing: 22,80,443, tcp
2. I can manually curl from the server
3. inspecting the nginx set-up `docker exec nginx-proxy nginx -T` appears to show everything correctly configured with the right urls
4. acme-companion version is: `nginx-proxy-acme  | Info: running acme-companion version v2.2.7-5-gdefde43`
5. Connections - both with browsers and something like netcat to 80 or 443 are timing out, not being rejected. 22 is working.

I'm not sure how to proceed. Does Ubuntu 22 need some extra configuration as compared to ubuntu 20? Have I missed something?
