### DISCUSSION TITLE
How can I enable acme.sh notifications?

### DISCUSSION THREAD

**Discussion by jdevera** [nginx-proxy/acme-companion#1199] [Q&A]
Is there access to configuring acme.sh's notifications, e.g. discord in this container?

**Comment by mvantoor** [comment]
Hi there, I managed to configure the acme.sh [notify](https://github.com/acmesh-official/acme.sh/wiki/notify) option for one of the build-in services [Pushover](https://pushover.net/).

I am using docker compose and I enabled acme.sh notify for pushover by adding the required environment variables and overruling the containers default CMD with the compose `command`. Below is an example of the service configuration I use:

```yaml
services:
  ...
  acme-companion:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion:2.6
    restart: unless-stopped
    environment:
      ...
      DEFAULT_EMAIL: [your-email]
      # Required for notifications via Pushover
      PUSHOVER_TOKEN: ${PUSHOVER_TOKEN_ACME_SH}
      PUSHOVER_USER: ${PUSHOVER_USER_KEY}
    command: >
      bash -c "acme.sh --set-notify --notify-hook pushover --notify-source acme-companion --config-home /etc/acme.sh/[your-email] && /app/start.sh"
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
``` 

Probably not the nicest solution but I think that if you follow this principle you can configure the notify service of your desire.
