### DISCUSSION TITLE
Docker renewing certificate(s) on startup even if certificate exists

### DISCUSSION THREAD

**Discussion by stevmon** [nginx-proxy/acme-companion#796] [Q&A] [answered]
We are trying to switch a client to use jrcs for certificates so we can use v2 for letsencrypt certificates.

I have a test environment set up using docker-compose since there are big changes to the docker-compose.yml  file.

I was using the staging URL in the YML file but wanted to check to make sure that we could retrieve a "real" certificate for the site and not have to accept a self-signed certificate. (I think that was what the browser needed...)

So I commented out the line "#      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory" in the YML file and everything seemed well. The certificate was accepted in the browser no problem.

But we noticed that each time I performed a "docker-compose down" and then a "docker-compose up" it would reload/pull new certificates for the site.

I don't think this should be normal operation as the certificates should already be persistent according to all I have read.

A couple of excerpts that I think might be relevant from the logs:

```console
letsencrypt-proxy    | Info: running acme-companion version v2.1.0-5-g1b01042
nginx-proxy          | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy          | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
...
nginx-proxy          | dockergen.1 | 2021/05/04 17:29:33 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
nginx-proxy          | dockergen.1 | 2021/05/04 17:29:33 Running 'nginx -s reload'
...
letsencrypt-proxy    | Warning: '/etc/acme.sh' does not appear to be a mounted volume.
letsencrypt-proxy    | Info: Custom Diffie-Hellman group found, generation skipped.
```

My YML file is as follows:

```yaml
version: "2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
      
  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
#      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
      DEFAULT_EMAIL: mail@sio.midco.net
      NGINX_PROXY_CONTAINER: nginx-proxy
 
 
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - ./logs/mariadb:/var/log/mysql
      - ./mariadb-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    container_name: mariadb
 
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    expose:
      - 80
    restart: unless-stopped
    volumes:
      - ./webroot:/var/www/html
      - ./logs/wordpress:/var/log/wordpress
    environment:
      VIRTUAL_HOST: HOST.com
      LETSENCRYPT_HOST: HOST.com
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_NAME: dbname
      WORDPRESS_DB_PASSWORD: dbpass
      WORDPRESS_TABLE_PREFIX: prefix
    container_name: wordpress
 

networks:
  default:
    external:
      name: nginx-proxy
 
volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
```
  
  
Is it normal behavior to re-fetch certificates on startup?  If it is my concern is that on the production server if we are doing other updates or changes that might require multiple restarts I might run out of quota for certificates and mess up the website for customers as far as certificates go.

According to the 120,000 YML files I have reviewed the certificate(s) should be persistent but that does not seem to be the case.

Any idea what I am missing?

Thanks!

**Comment by buchdag** [comment]
Hi, the front of the README has a warning about this:

> **Required read if you use the `latest` version** : the `v2.0.0` release of this project mark the switch of the ACME client used by the Docker image from [**simp.le**](https://github.com/zenhack/simp_le) to [**acme.sh**](https://github.com/acmesh-official/acme.sh). This switch result in some backward incompatible changes, so please read [this issue](https://github.com/nginx-proxy/acme-companion/issues/510) and the updated docs for more details before updating your image. The single most important change is that the container now requires a volume mounted to `/etc/acme.sh` in order to persist ACME account keys and SSL certificates. The last tagged version that uses **simp_le** is `v1.13.1`.

Also please note that this project's name and DockerHub registry have changed. We are still pushing to `jrcs/letsencrypt-nginx-proxy-companion` but it's considered legacy, the new registry is `nginxproxy/acme-companion`.

Lastly, I'd strongly advise against using `latest` version of any image in production. I'd rather use versioned tags whenever available, and update the versions used in a controlled manner (and read the project's release notes ^^) to avoid surprises like this one.

**Comment by stevmon** [comment, marked as answer]
Thank you for your response.

I had read that section but did not really comprehend how to implement it. I followed the links and did not gather any information that was specific enough for me and actually confused me on what I needed to do.

In fact I spent part of the day searching for items pertaining to acme.sh and implementing it in a YML file - which really took me further off course.

But! I finally did realize that what I needed to do was to create a volume in the volumes section of both my letsencrypt-proxy and nginx-proxy containers in the YML containing:

      - letsencrypt-acme:/etc/acme.sh

This was not obvious to me from that snippet. Also there is a link further down in that page that was supposed to be related to persistence. There was no reference information there about needing that volume. So that maybe should be adjusted?

Thanks again for your response.

**Comment by Pryla** [comment]
Thank you both so much!

1.

> But! I finally did realize that what I needed to do was to create a volume in the volumes section of both my letsencrypt-proxy and nginx-proxy containers in the YML containing:
> ```
>   - letsencrypt-acme:/etc/acme.sh
> ```

2.

> Also please note that this project's name and DockerHub registry have changed. We are still pushing to `jrcs/letsencrypt-nginx-proxy-companion` but it's considered legacy, the new registry is `nginxproxy/acme-companion`.
> 

Those two bits of information helped me out. I spent so much time and a sleepless night with this. The linked issue might not be too helpful for newbies.

And btw: [docker hub](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion) for `jrcs/letsencrypt-nginx-proxy-companion` points out that the latest version for acme 1.0 is `v1.11` and not `v1.13.1` or what am I missing here?

Thank you!

**Comment by buchdag** [comment]
@stevmon @Pryla any PR with clarification to the README.md are welcome

> And btw: [docker hub](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion) for `jrcs/letsencrypt-nginx-proxy-companion` points out that the latest version for acme 1.0 is `v1.11` and not `v1.13.1` or what am I missing here?

Unfortunately you're not missing anything, I don't have direct modification right over the Readme of https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion, I want to fix this but I haven't had the time yet.

**Comment by buchdag** [comment]
> But! I finally did realize that what I needed to do was to create a volume in the volumes section of both my letsencrypt-proxy **and nginx-proxy containers** in the YML containing

You don't need to add this volume to the nginx-proxy container, only the acme-companion container reads from / writes to `/etc/acme.sh`

**Reply by zanzara** [reply]
But the 
```
- 'certs:/etc/nginx/certs'
```
volume must still be present on both contianer? 
('nginxproxy/nginx-proxy' and  'nginxproxy/acme-companion')

**Reply by buchdag** [reply]
Yep (or on the three containers `nginx` + `docker-gen` + `acme-companion` if you're using this setup).

Additionally it won't cause any malfunction to mount `/etc/acme.sh` to the `nginx-proxy` container, but it contains private data (your ACME account keys) that should ideally not be mounted on a container exposed to the outside.

**Reply by zanzara** [reply]
Thx.
To get you right:
Changing to the new `/etc/acme.sh` I will be able to `up` and `down` my proxied container w/o having this annoying letsencrpyt restriction of max 5 new certificates a week?!

**Reply by zanzara** [reply]
edit:
unfortunately I cannot test it now, cause I have apparently to wait some days until the rate limit is refreshed again for my subdomains.
I can live with the browser complains, which comes with the use of certs staging image `https://acme-staging-v02.api.letsencrypt.org/directory`   but using my web-app with capacitor on the phone, it does not work with my backend
(cause capacitor settings does not accept there such invalid https).
Or am I wrong here?

**Reply by buchdag** [reply]
To recap, if you don't have this volume mounted to `/etc/acme.sh`, acme.sh can't keep track of the certificates it already obtained because this state is erased along with the container on `docker compose down`.

On the next `docker compose up`, acme.sh won't find any trace of the already obtained certificate inside the container `/etc/acme.sh` folder and will re-create those certificate. This will in turn probably trigger Let's Encrypt rate limiting of 5 cert / domain / week.

Persisting `/etc/acme.sh` means that on `docker compose up`, acme.sh find the already obtained certificates and don't ask for them to be issued again.

Let me know if this is clear to you.

**Reply by zanzara** [reply]
Yes, it's clear.
But to confirm now, if it really works for me as you describe, unfortunately I have to wait now some days until rate limiting is voided again.

**Reply by buchdag** [reply]
> unfortunately I have to wait now some days until rate limiting is voided again.

Yep 😞 

Additionaly, `/etc/nginx/certs` is required by:

- `acme-companion` because this is the container that writes the certificates to this folder
- the `docker-gen` process because it needs to find the certificate files with the proper path / name to enable SSL
- the `nginx` process because it reads the certificates and private keys from this folder

In `nginx-proxy`, the `nginx` and `docker-gen` processes are running inside the same container.

**Reply by stevmon** [reply]
Actually zanzara should be able to add the line with ACME_CA_URI below and use a test certificate:

  letsencrypt-proxy:
    image: nginxproxy/acme-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
      - letsencrypt-acme:/etc/acme.sh
    environment:
      **ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory**
      DEFAULT_EMAIL: somemail@yahoo.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    restart: always

**Reply by zanzara** [reply]
Thx, but this is what I just did in the meantime (look at my post above).
The issue with the staging image is, that browsers are complaining too intensive about the invalid cert.
Users out there won't click through the browser's exceptions buttons to see however the page -  which is rather reasonable.

Even worse as app artifact on the phone. Cause I cannot configure capacitor that way, that it accepts such an invalid cert.

So in the end, I have to wait now until rating limit is refreshed again for my subdomains.

**Reply by buchdag** [reply]
@zanzara you can also get valid certificates from another ACME compatible CA like [Zero SSL](https://github.com/nginx-proxy/acme-companion/blob/main/docs/Zero-SSL.md).

Let me know if Zero SSL usage isn't clear enough in the docs.

**Reply by zanzara** [reply]
Hooray, you made my day (although it's midnight here now) !
It works like charm with Zero SSL (as you wrote it in your docs). Great. Also app is working again now.

I'm not stucking so deep in this certification stuff as you obviously. I did only know about LetsEncrpyt.
So, good luck and good night

**Reply by wooogy-dev** [reply]
@buchdag Hello! Now I'm using Zero SSL because of rate limiting issue
my docker-compose file is like this
```
version: "3.9"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro      
      - ../nginx/log:/var/log/nginx 
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - conf:/etc/nginx/conf.d
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx-proxy"
    restart: always

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: nginxproxy/acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam:ro
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme.zerossl.com/v2/DV90
      - ZEROSSL_API_KEY="my api key.."
  
  user-frontend:
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
    expose:
      - 3000

  admin-frontend:
    environment:
      - VIRTUAL_HOST=admin.${HOST}
      - LETSENCRYPT_HOST=admin.${HOST}
    expose:
      - 3000

  express:
    environment:
    - VIRTUAL_HOST=api.${HOST}
    - LETSENCRYPT_HOST=api.${HOST}
    expose:
      - ${PORT}
  
  adminer:
    environment:
    - VIRTUAL_HOST=db.admin.${HOST}
    - LETSENCRYPT_HOST=db.admin.${HOST}
    expose:
      - 8080

volumes:
  certs:
  conf:
  vhost:
  html:
  dhparam:
  acme:
```

some of container is work but some of still doesn't have ssl verification...
Is there any wrong in my compose file or should I add something on it?
