### ISSUE TITLE
How to stop requesting of NEW certificates?

### ISSUE THREAD

**Issue by richardARPANET** [nginx-proxy/acme-companion#1003]
Whenever I restart the container, it goes through all my domains and requests NEW certs. I want it to use the existing non-expired certs.

This is a problem as it is now hitting 429 error from letsencrypt server.

**Comment by richardARPANET** [comment]
I have the following:

```yaml
  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /data/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /data/nginx-proxy/html:/usr/share/nginx/html
      - /data/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/nginx-proxy/acme.sh:/etc/acme.sh

    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
```
