### ISSUE TITLE
Key file is world readable

### ISSUE THREAD

**Issue by codewithmartin** [nginx-proxy/acme-companion#1007]
Bug description
-----------------

keyfile stored in acme.sh/ and also installed to certs/ is world readable (0644). It should be 0600.

**Comment by joeyfigaro** [comment]
Could use attention

**Comment by buchdag** [comment]
I'll handle this by the end of the week for files in `/etc/nginx/certs`.

[Unfortunately it looks like we can't touch permissions of private keys stored in `/etc/acme.sh` without breaking everything.](https://github.com/nginx-proxy/acme-companion/actions/runs/4529396721)

I'd strongly advise against using [bind mounts](https://github.com/nginx-proxy/acme-companion/blob/main/docs/Persistent-data.md#host-volumes) for the `/etc/acme.sh` volume.

**Comment by te-online** [comment]
Hey there 👋  Is this included in the `latest` docker tag?

I'm running into an issue with permissions with the latest image. My usecase is that I mount the certs volume into an InfluxDb container to re-use the certificate for its services.

Like so:

```
# ...
nginx-proxy-letsencrypt:
  <<: [*restart_policy, *network, *logging]
  image: nginxproxy/acme-companion
  container_name: nginx-proxy-lets-encrypt
  depends_on:
    - "nginx-proxy"
  volumes:
    - nginx-certs:/etc/nginx/certs:rw
    - nginx-vhost:/etc/nginx/vhost.d
    - nginx-html:/usr/share/nginx/html
    - nginx-dhparam:/etc/nginx/dhparam
    - nginx-acme:/etc/acme.sh
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - DEFAULT_EMAIL=${DEFAULT_EMAIL}
  userns_mode: 'host'

influxdb:
  <<: [*restart_policy, *network, *logging]
  image: influxdb:1.8.10
  container_name: influxdb
  volumes:
    # Mount for influxdb data directory
    - influxdb-data:/var/lib/influxdb
    # Mount for influxdb configuration
    - ./influxdb/config/:/etc/influxdb/
    # Re-use Let's Encrypt certificates for API
    - nginx-certs:/etc/ssl/certs:ro
  ports:
    # The API for InfluxDB is served on port 8086
    - '8086:8086'
    - '8082:8082'
    # UDP Port
    - '8089:8089/udp'
  environment:
    - INFLUXDB_DB=${INFLUXDB_DB}
    - LOGSPOUT=ignore
  env_file:
    - influxdb.env
```

The InfluxDb container now refuses to start, because its user doesn't have permission to access the certificate.
This is especially complicated, as the InfluxDb container uses user namespace mapping (because it safely can), but acme-companion can't use user namspace mapping from my experience, so we're guaranteed to have different user ids here, making it impossible to re-use the certificates.

Maybe you have a magic idea on how to fix this? 😊
