### ISSUE TITLE
Error: Docker host socket at /var/run/docker.sock is not readable

### ISSUE THREAD

**Issue by andrei-datcu** [nginx-proxy/acme-companion#1179]
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
nginxproxy/acme-companion   latest              a4f6c6c20efa        3 weeks ago         46.6MB
```
-----------------

```console
Info: running acme-companion version v2.5.1-6-gea11f22
Error: Docker host socket at /var/run/docker.sock is not readable. Please check user permissions
If you are in a SELinux environment, try using: '-v /var/run/docker.sock:/var/run/docker.sock:z'

```

Note that the socket seems to be readable. Binding with `:z` doesn't make any difference:

Proof:
```console
348d706f16fe:/app# bash ./entrypoint.sh /bin/bash /app/start.sh
Info: running acme-companion version v2.5.1-6-gea11f22
Error: Docker host socket at /var/run/docker.sock is not readable. Please check user permissions
If you are in a SELinux environment, try using: '-v /var/run/docker.sock:/var/run/docker.sock:z'
348d706f16fe:/app# ls -alh /var/run/docker.sock 
srw-rw---- 1 root 998 0 Aug 12 13:24 /var/run/docker.sock
348d706f16fe:/app# 
exit
```

Executing `start.sh` **works**.

Docker host
-----------------

 - OS: `Debian 10 Linux debian 4.19.0-27-amd64 #1 SMP Debian 4.19.316-1 (2024-06-25) x86_64 GNU/Linux`
 - Docker version:
```Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Other (intersting info):

`test -r` fails for any file in the container
`test -S /var/run/docker.sock` is successful

**Comment by buchdag** [comment]
Hi.

Could you provide your complete nginx-proxy + acme-companion setup ?

Are you running SELinux or something similar on this host ?

I noticed the version of Docker you're running is almost five years old, maybe this is related, maybe not.

**Comment by vianmiranda** [comment]
Running into the same issue as OP. I'm on version 27.4.1 running Ubuntu. SELinux status is disabled. I'm using docker compose to build and run `nginx-proxy` + `acme-companion`. I have provided the `.yaml` file below.

```yaml
services:
    nginx:
        image: nginxproxy/nginx-proxy:2561-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
    acme-companion:
        image: nginxproxy/acme-companion:2.5
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - acme:/etc/acme.sh
        environment:
            - DEFAULT_EMAIL=${EMAIL}
volumes:
    certs:
        driver: local
    html:
        driver: local
    acme:
        driver: local
```
        
Once composed, `acme-companion` exits with code `(1)`. When checking the docker logs for the container, I get a similar error message. 

```
Error: Docker host socket at /var/run/docker.sock is not readable. Please check user permissions
If you are in a SELinux environment, try using: '-v /var/run/docker.sock:/var/run/docker.sock:z'
Info: running acme-companion version v2.5.1-10-g47a48d7
```

Trying `.../docker.sock:z` does not resolve it, nor do some of the other solutions online. I tried `chmod 666` and `777` (I'm aware it's not secure) for testing and I still got the same issue. Although, there is a good chance I'm going about this all wrong.

**Comment by andrei-datcu** [comment]
No SELinux, the host is a 2vCPU VPS.
Here's the relevant part of the docker compose file:
```yml
    nginx: # includes static files
        image: jwilder/nginx-proxy:alpine
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nginx_certs:/etc/nginx/certs:ro
            - nginx_vhost:/etc/nginx/vhost.d
            - nginx_dhparam:/etc/nginx/dhparam
            - nginx_html_challange:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        depends_on: 
            - app

    letsencrypt:
        image: nginxproxy/acme-companion
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - nginx_certs:/etc/nginx/certs:rw
            - nginx_vhost:/etc/nginx/vhost.d
            - nginx_dhparam:/etc/nginx/dhparam
            - nginx_html_challange:/usr/share/nginx/html
            - acme:/etc/acme.sh
        environment:
            - DEFAULT_EMAIL=${LETSENCRYPT_ALERT_EMAIL}
```

The docker engine on the host is indeed ancient. Reversing the initial checks in the entrypoint script would work, though: if `test -S` fails, then do a `test -r` to decide on the what error message is shown. Would that be acceptable?
