### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by David-Ter** [nginx-proxy/acme-companion#1190]
I am using image nginxproxy/acme-companion with nginxproxy/nginx-proxy for generating Reverse Proxy configs on my server
I use the latest version for all images
My docker-compose.yaml
```
volumes:
  nginx_conf:
  nginx_html:
  nginx_certs:
  nginx_vhost:
  acme:

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTPS_METHOD=noredirect
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    networks:
      - vault-docker

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    restart: always
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    networks:
      - vault-docker

  acme-companion:
    image: nginxproxy/acme-companion:2.4.0
    container_name: nginx-proxy-acme
    restart: always
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx_certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - vault-docker

networks:
  vault-docker:
    external: true
```
 
 I test a web server docker but when i go to https://subdomain.domain.fr i get "HTTP ERROR 500" but http works fine
```
services:

  suitecrm:
    image: suitecrm:8
    container_name: suitecrm8
    #ports:
    # - '80:80'
    # - '443:443'
    environment:
      - SUITECRM_DATABASE_HOST=database_app
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=root
      - SUITECRM_DATABASE_NAME=suitecrm
      - SUITECRM_DATABASE_PASSWORD=PASSWORD
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - VIRTUAL_HOST=suitecrm.DOMAIN.fr
      - LETSENCRYPT_HOST=suitecrm.DOMAIN.fr
        #- CERT_NAME=default
    restart: unless-stopped
    external_links:
      - database_app
    volumes:
      - "./web:/var/www/html"
      #- "./config/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./logs:/var/log/apache2/"
      - "./config/sites-enabled:/etc/apache2/sites-enabled"
      - "./config/php.ini:/usr/local/etc/php/php.ini"
    networks:
      - vault-docker

networks:
   vault-docker:
     external: true
```
 
 The certificates are created in /var/lib/docker/volumes/proxy_nginx_certs/_data
```
root@privateserver:/var/lib/docker/volumes/proxy_nginx_certs/_data# ll
total 28
drwxr-xr-x 4 root root 4096 Apr  2 17:18 ./
drwx-----x 3 root root 4096 Apr  1 17:17 ../
-rw-r--r-- 1 root root 1870 Apr  1 17:17 default.crt
-rw------- 1 root root 3272 Apr  1 17:17 default.key
-rw-r--r-- 1 root root  769 Apr  1 17:17 dhparam.pem
drwxr-xr-x 2 root root 4096 Apr  1 17:18 portainer.DOMAIN.fr/
lrwxrwxrwx 1 root root   36 Apr  1 17:18 portainer.DOMAIN.fr.chain.pem -> ./portainer.DOMAINfr/chain.pem
lrwxrwxrwx 1 root root   40 Apr  1 17:18 portainer.DOMAIN.fr.crt -> ./portainer.DOMAIN.fr/fullchain.pem
lrwxrwxrwx 1 root root   13 Apr  1 17:18 portainer.DOMAIN.fr.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   34 Apr  1 17:18 portainer.DOMAIN.fr.key -> ./portainer.DOMAIN.fr/key.pem
drwxr-xr-x 2 root root 4096 Apr  1 17:20 suitecrm.DOMAIN.fr/
lrwxrwxrwx 1 root root   35 Apr  1 17:20 suitecrm.DOMAIN.fr.chain.pem -> ./suitecrm.DOMAIN.fr/chain.pem
lrwxrwxrwx 1 root root   39 Apr  1 17:20 suitecrm.DOMAIN.fr.crt -> ./suitecrm.DOMAIN.fr/fullchain.pem
lrwxrwxrwx 1 root root   13 Apr  1 17:20 suitecrm.DOMAIN.fr.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root root   33 Apr  1 17:20 suitecrm.DOMAIN.fr.key -> ./suitecrm.DOMAIN.fr/key.pem
```
 
Configuration issue in nginproxy ?
 
DNS and domains are managed by OVH

Thanks for your help
