### ISSUE TITLE
VIRTUAL_HOST_MULTIPORTS support

### ISSUE THREAD

**Issue by poehlert** [nginx-proxy/acme-companion#1192]
nginx-proxy and dockergen support a convenient advanced feature for containers that may [expose multiple services/ports](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports) that you want to put behind different domains. The MinIO container is a great example, which hosts the data plane and control plane as separate services on separate ports. Running multiple containers is not an option in this case as they would compete for state.

# Desired outcome
Support VIRTUAL_HOST_MULTIPORTS. 

Continuing with the MinIO example:
``` yaml
services:
  minio-container:
    image: somebodys/minio
    container_name: minio-container
    environment:
      VIRTUAL_HOST_MULTIPORTS: |-
        s3.example.com:
          "/":
            port: 9000
        minio.example.com:
          "/":
            port: 9001
```
Would get certificates s3.example.com,minio.example.com and make them available for the nginx config.

**Comment by buchdag** [comment]
Hi

I thought this worked as expected:

```yaml
services:
  minio-container:
    image: somebodys/minio
    container_name: minio-container
    environment:
      LETSENCRYPT_HOST: "s3.example.com,minio.example.com"
      VIRTUAL_HOST_MULTIPORTS: |-
        s3.example.com:
          "/":
            port: 9000
        minio.example.com:
          "/":
            port: 9001
```

Does it not ?
