### ISSUE TITLE
Support wildcard certificates with ACMEv2

### ISSUE THREAD

**Issue by raqbit** [nginx-proxy/acme-companion#319]
On January 27 letsencrypt will make star certificates fully available via the ACME v2 protocol. 
Are you planning on adding support for this?

**Comment by buchdag** [comment]
Wilcard certs will require `dns-01` challenge and simp_le only support `http-01`,  so they won't be available through letsencrypt-nginx-proxy-companion.

https://github.com/zenhack/simp_le/issues/101

**Comment by Raqbit** [comment]
Well that's a bummer. As Python-acme is part of certbot I'd guess they will implement v2 soon-ish, and then simple_le will able to support it as well in the future. Anyways, thanks!

**Comment by buchdag** [comment]
Unfortunately it's not as simple as that, let me clarify : support for ACME V2 will be implemented in simp_le, but `dns-01` challenge won't.

`dns-01` challenge is not specific to ACME v2 and the original simp_le developer (@kuba) made the explicit choice to limit simp_le to `http-01` challenge from the beginning (you can see it in the [manifesto](https://github.com/zenhack/simp_le#manifesto), point 3).

**Comment by buchdag** [comment]
@Raqbit I'm re-opening so the issue and the reason why we won't support wildcard certs have better visibility.

**Comment by almereyda** [comment]
Please see https://github.com/zenhack/simp_le/issues/101#issuecomment-372773310 for updates on the upstream issue, since the v2 endpoint has finally been released to production.

**Comment by buchdag** [comment]
@almereyda as told in my first message on this issue and on the `simp_le` issue you mentioned, wilcard certificates requires `dns-01` challenge support, which is absent from `simp_le` (and there are no plans to add it).

**Comment by Dragnucs** [comment]
I am curious. Can't simp_le be replaced with another components that could handle dns-01 challenge? If not, what are our options? Can't we hack the configuration a bit on our end to support it?

**Comment by buchdag** [comment]
It could, `letsencrypt-nginx-proxy-companion` is pretty much "just" bash automation around `simp_le` and `nginx-proxy`, there is nothing preventing someone from re-writting it to use another ACME client and provide additional features. As usual with small open source projects the only real issues are the amount of work necessary and the time it takes.

I've been thinking for a while about doing a fork of this project using `certbot` instead of `simp_le` but it's pretty far from a drop-in replacement as the two behave in very different ways. I lack the time to do more than experiment a bit with the idea once in a while.

As for other options, the most serious is probably switching to a bigger project like https://github.com/containous/traefik

To be honest I have my doubts about the long term viability of the `nginx-proxy` / `docker-gen` solution as it's now extremely hard to get contributions merged to those projects (mostly due to the fact that their creator is very busy working at influxdb, I guess. That's understandable).

**Comment by Dragnucs** [comment]
@buchdag thank you for your reply.

**Comment by almereyda** [comment]
The simp_le issue mentions that they are planning to support the DNS-01
challenge soon'ish.

**Comment by buchdag** [comment]
Errr no it does not.

We (zenhack and I) said on that issue that ACME v2 support is planned (we said nothing about when, and it might turn out to be harder than expected) and that [`dns-01` is out of scope](https://github.com/zenhack/simp_le/issues/101#issuecomment-356193059).

Again `dns-01` challenge is required to obtain a wildcard certificate through the Let's Encrypt ACME v2 endpoint, but they are not one and the same thing: implementing ACME v2 does not imply implementing `dns-01` challenge at all.

**Comment by evertramos** [comment]
@buchdag Thanks for your contribution!!! Traefik works really fine with it!!! I am doing some tests around it and it seems pretty stable as well. Since I have a couple servers running this repo It will take a couple months to release something usefull, but thank in advance!

**Comment by BirkhoffLee** [comment]
I’m sorry, I didn’t mean to say that. I’m not a native English speaker so..
haha

I’ll try to dig into the code and see if I can add a hint to the error when
I have free time :)

Sorry again for what I said, and thanks to everyone for the contribution to
the awesome project!

**Comment by buchdag** [comment]
My bad, I did not realize you were a non native english speaker. 😅

You're right with the fact that some warnings about unsupported features (as of now) like ACME V2 endpoints and wildcard certificates should be added. I'll try to add this to `dev` this week.

**Comment by BirkhoffLee** [comment]
Thanks 😄

**Comment by xiaods** [comment]
hi team, how long we can support ACME v2 feature?

**Comment by whlsxl** [comment]
@buchdag actually traefik use [lego](https://github.com/xenolf/lego) as LE lib

**Comment by ejbp** [comment]
While wildcard is not implemented, there's any workaround to minor work effort on setting up a wildcard configuration on nginx all the other benefits of this image? e.g. Can I manually generate a wildcard certificate ant let know "letsencrypt-nginx-proxy-companion" to use these custom certificates instead of try to create/renew new ones? 

I tried to have my custom certificates on certificates path but they are still replaced by the single domain certificate that "letsencrypt-nginx-proxy-companion" generates. I can in a ugly way limit the permissions to read only for my custom certificates but still, the let's encrypt api will be called if I need to restart the docker which may enter in a out of limit requests to letsencrypt.

Meanwhile, it would be great if this will be implemented shortly or if I really need to consider other solution :( 

Thanks in advance.

**Comment by buchdag** [comment]
letsencrypt-nginx-proxy-companion does not "use" certificates. It handle their creation, renewal, and some symlink work so that nginx-proxy can pick them up.

The application you want to use your externally obtained certificates with is nginx-proxy and that amount to following their existing doc and doing a naming or symlinking job similar to what the companion do.

**Comment by ejbp** [comment]
I understand your point and makes sense. Though, I'm not able to have a mixed configuration with domains that are under letsencrypt-nginx-proxy-companion management and domains that are not, having in mind that jwilder/nginx-proxy is the same and using the same certs dir for all domains. What's happening is that letsencrypt-nginx-proxy-companion is removing my custom certificates since it considers that they are unsed.

log:
```
letsencrypt-nginx-proxy-companion    | Symlinked domains: yyy.com xxx.com
letsencrypt-nginx-proxy-companion    | Enabled domains: xxx.com
letsencrypt-nginx-proxy-companion    | Disabled domains: yyy.com
letsencrypt-nginx-proxy-companion    | Some domains are disabled. Check them to remove unused symlinks.
letsencrypt-nginx-proxy-companion    | 
letsencrypt-nginx-proxy-companion    | Checking domain yyy.com: 
letsencrypt-nginx-proxy-companion    | Checking yyy.com.crt - removing.
letsencrypt-nginx-proxy-companion    | Checking yyy.com.key - removing.
letsencrypt-nginx-proxy-companion    | Checking yyy.com.dhparam.pem
letsencrypt-nginx-proxy-companion    | Checking yyy.com.chain.pem - removing.
letsencrypt-nginx-proxy-companion    | Unused domains checking is finished.
```

docker-compose.yml:

```
services:
  letsencrypt_nginx_proxy_companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - load_balancer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${LETSENCRYPT_CERTS_PATH}:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=load_balancer
  load_balancer:
    image: jwilder/nginx-proxy
    container_name: load_balancer
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/load-balancer/nginx-proxy-vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
      - "${LETSENCRYPT_CERTS_PATH:/etc/nginx/certs:ro"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      - ENABLE_IPV6=true
    restart: always
  website:
    container_name: website
    image:  ${IMAGE_WEBSITE}
    ports:
      - 5555:80
    environment:
      - VIRTUAL_HOST=xxx.com
      - LETSENCRYPT_HOST=xxx.com
      - LETSENCRYPT_EMAIL=production@xxx.com
  custom_certificates_website:
    container_name: custom-certificates-website
    image:  ${IMAGE_CUSTOM_CERTIFICATES_WEBSITE}
    ports:
      - 5556:80
    environment:
      - VIRTUAL_HOST=yyy.com,*.yyy.com
```

**Comment by buchdag** [comment]
Ok that's a bug, it should not happen. Do you mind opening a separate issue so we can work toward fixing it ?

**Comment by speshak** [comment]
FWIW: I forked this a while back to use acme.sh instead of simp_le explicitly so I could do dns-01 validation via AWS Route53.  I haven't tried using wildcard certs with my fork, but if someone really wanted to they could try: https://github.com/speshak/docker-letsencrypt-nginx-proxy-companion/tree/acme.sh

**Comment by buchdag** [comment]
A v2.0 version using [`acme.sh`](https://github.com/Neilpang/acme.sh) is being worked on and will be available at least on the `dev` branch by the end of march (that's an estimate, not a hard deadline).

This new version will be able to use ACME v2 endpoint (and will probably default to them) and to issue ECDSA certificates but I'm not sure yet if the ability to issue wildcard certificate will be present as soon as v2.0 or on a later version.

Some feature will have to be handled very differently than on the current version (namely pretty much everything about ACME accounts and emails), the container will require some additional configuration and all existing certs will have to be issued again (with new domain authorisations).

I've considered and tested [`lego`](https://github.com/xenolf/lego) as suggested by @whlsxl but it does not fit as weel as `acme.sh` and require too much work (it pretty much require to build all the new / existing / changed / renewed cert logic from the ground up).

Also considering(ed) [`dehydrated`](https://github.com/lukas2511/dehydrated) but it does not have built in DNS manipulation and would require pairing with something like [`lexicon`](https://github.com/AnalogJ/lexicon) to enable automated wildcard certificate issuance.

**Comment by Greek64** [comment]
@buchdag 
I was about to make of "proof of concept" PR where I swap `simp_le` for `acme.sh`, but as I see you are already working on integrating `acme.sh`.
I would suggest that the first version only swaps the client and does only ensure backwards compatibility, before adding new features like ECDSA, stapling, wildcard, etc...
Will the acme client be selectable (e.g. via an environmental variable) or will the project as a whole move to the new client?

**Comment by buchdag** [comment]
Backward compatibility might be really hard depending on what you expect to be backward compatible, ie most environment variables and config parameters won't change, but reusing existing data will be either hard (certificates and private key) or very hard / not possible (ACME account keys).

**Comment by buchdag** [comment]
I'll open another separate issue with more details about were I am now with the `acme.sh` version and what the issues / challenges are so we can discuss this as soon as I'll have some time.

**Comment by maximkrusina** [comment]
In between, I found this - I hope it will help someone:
https://github.com/adferrand/docker-letsencrypt-dns

**Comment by kkalugerov** [comment]
Is there any development on the problem ?

**Comment by buchdag** [comment]
Support for wildcard certificates will come eventually but isn't planned anytime soon.

**Comment by buchdag** [comment]
More accurately, the plan so far is:
- switch to an [ACME v2 compatible version of  `simp_le`](https://github.com/zenhack/simp_le/pull/119) before the november deadline
- then switch from `simp_le` to `acme.sh` in the months following that
- when the `acme.sh` based version is stable enough, start working on `DNS-01` challenge and wildcard certificate support

I really hope that I'll be able to get to the last point in the next ~4 months but I really can't predict when I'll have free time and how much.

**Comment by dm17** [comment]
Does this mean all of you who want www.example.com and example.com to work use both here:
VIRTUAL_HOST=example.com,www.example.com
LETSENCRYPT_HOST=example.com,www.example.com
?

**Comment by Greek64** [comment]
> Does this mean all of you who want [www.example.com](http://www.example.com) and example.com to work use both here:
> VIRTUAL_HOST=example.com,www.example.com
> LETSENCRYPT_HOST=example.com,www.example.com
> ?

Well yes, but since I guess `example.com` and `www.example.com` will point to the same thing a CNAME record in your DNS settings is the more elegant way to solve this.

**Comment by buchdag** [comment]
A pre-release with ACME v2 support is available as tag `v1.12-rc.1`. I can't guarantee this is fully production ready yet.

This is just part of the upcoming switch to ACME v2 protocol prior to the November 1st deadline I alluded to in my [previous message](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-515758935), it does not bring support for wildcard certificates.

I had way less free time than expected since the end of July, so things are going rather slowly 😒

**Comment by nffdiogosilva** [comment]
Just like to say that I've just tested the tag `v1.12-rc.1` and according the logs, it generated the certificate with no hiccup whatsoever. So far so good.

Congratulations on this amazing tool to automate production environments!

**Comment by stradarius** [comment]
Confirm that v1.12-rc.1 works with ACME v2 . I needed to upgrade:
While it was possible 2 days ago to create certificates with ACME v1, today I was not able to create any new certificate with ACME v1 - maybe duedate is not really beginning of november?

**Comment by janus-reith** [comment]
See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/3

> We will be beginning brown-outs for new ACME v1 registrations for the production environment for the following dates of this year:
> 
> October 10th to October 11th
> October 16th to October 18th
> October 31st onward
> We will be permanently disabling new ACME v1 registrations in the production environment on October 31st.

I can confirm that as of today ACMEv1 was not supported for me anymore:
`ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.`

**Comment by buchdag** [comment]
ACME v2 support has been merged to master in #590 

`latest` is now compatible with ACME v2  and tagged version `v1.12` is now available.

`stable` should be updated to `v1.12` by the end of the month.

**Comment by kopax** [comment]
Hi, I am discovering this project. I see why the issue has been reopened but I also see there is a v1.12 solution for it. Is this finally solved? Thanks for sharing!

**Comment by buchdag** [comment]
> This is just part of the upcoming switch to ACME v2 protocol prior to the November 1st deadline I alluded to in my [previous message](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-515758935), **it does not bring support for wildcard certificates**.

**Comment by benben** [comment]
great work. thank you! Is there a way to support your work with a donation?

**Comment by almereyda** [comment]
Now following suite with the release of v2 through #510 and #719, it appears even more possible to use `dns-01` ACME v2 challenges with the companion.

In https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/510#issuecomment-747608623 @pini-gh communicated the existence of a fork --- that happens to find itself at https://github.com/pini-gh/docker-letsencrypt-nginx-proxy-companion in opposition to the link provided there --- that implements the requested change here. See the comparison in https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/compare/v2.0.1...pini-gh:dns-01-challenge

Would this deem a suitable moment to issue a Pull Request from this PoC and test and extend it against the maintainer's expectations?

**Comment by buchdag** [comment]
@almereyda as usual I'd really like to give users a roadmap and stick to it, but you saw how well it went [the last time I tried that](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-515758935).

Things I can say for now:
- yes, now that #510 / #719 are done, `dns-01` challenges support will be worked on
- there is some CI/CD and code refactoring work that I want to do before that
- also, improvements on logging and debugging
- I'll certainly start with @pini-gh fork and work with him on this if he wants to and has time to spare
- it will probably be way harder to create a working integration test for this feature than the feature itself

**Comment by MohammedNoureldin** [comment]
Hello, any news regarding DNS challenge support?

**Comment by xicond** [comment]
Is there a way to customize executed acme.sh when I want to do wildcard with dns-01 challenge, I'll use if-else per domain to append TOKEN and change to dns-01 challenge

**Comment by Miladiir** [comment]
Hi, what about #916, any plans to merge it?

**Comment by Hexalyse** [comment]
Bumping this issue since not a single comment has been posted in response to the PR #916 which seems to implement wildcard certificates.

Is it planned to be merged ? Or is this feature simply not planned to be implemented by the acme-companion devs for other reasons ?

**Comment by daweedm** [comment]
@Miladiir @Hexalyse the PR #916 is unfortunately too much specific to cloudfare (because it's checking for the existence of `CF_Token` environment variable). 

I have created a PR (#1022) for adding generic support for DNS challenges which is fully working for "non-wildcard" domains with minor changes to the code base and being not specific to any provider. 

Based on what I have read in the #916 , the PR #1022 may not require a lot of additional work in order to support wildcards domains, because wildcard certs are issued based on DNS challenge : I think it only require to update the `functions.sh` as it's done in #916, but to be confirmed by @buchdag

**Comment by PedroVallejo5** [comment]
Are there any updates on this? This feature is gonna help us a lot

**Comment by aaccioly** [comment]
If anyone is looking for a working alternative, here's an example of how to combine [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) with [adferrand/dnsrobocert](https://github.com/adferrand/dnsrobocert): [Script to deploy certificates generated with DNSroboCert to jwilder's nginx-proxy](https://gist.github.com/aaccioly/409205f5b87228cae7a69aafa31a0924?permalink_comment_id=4702163#gistcomment-4702163). It's working very well, feel free to use it in any way that you see fit.

**Comment by Cilenco** [comment]
For anyone searching for wildcard certificate support in [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy):

I've created a [docker image](https://github.com/Cilenco/lego-cron-wrapper) which is based on [go-acme/lego](https://github.com/go-acme/lego) and works perfectly well with nginx-proxy.
It supports all of their DNS providers and auto updates the certificates using cron before they get invalid.

**Comment by cistes44** [comment]
> I've created a [docker image](https://github.com/Cilenco/lego-cron-wrapper) which is based on [go-acme/lego](https://github.com/go-acme/lego) and works perfectly well with nginx-proxy.

I confirm, thanks a lot for this image! The documentation being extra slim, I share my `docker-compose.yml` file here, with ovh api and wildcard certificate generation. if you have another registar/dns provider, you can check the proper environment variables here : [https://go-acme.github.io/lego/dns/](https://go-acme.github.io/lego/dns/)

```
version: "2.4"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      proxy-network:

  lego-acme:
    image: cilenco/lego-cron-wrapper
    container_name: lego-acme
    command: >
      --accept-tos --email=mail@example.com --dns ovh
      --domains=*.example.com
    environment:
      - RUN_ARGUMENTS=--run-hook=/app/deploy
      - RENEW_ARGUMENTS=--renew-hook=/app/deploy
      - OVH_APPLICATION_KEY=<appkey>
      - OVH_APPLICATION_SECRET=<appsec>
      - OVH_CONSUMER_KEY=<conskey>
      - OVH_ENDPOINT=ovh-eu
    volumes:
      - certs:/app/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy.sh:/app/deploy
    networks:
      - proxy-network-internal

  website:
    image: httpd:alpine
    container_name: website
    restart: always
    volumes:
      - ./website:/usr/local/apache2/htdocs/:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    environment:
      - VIRTUAL_HOST=example.example.com
    networks:
      - proxy-network

volumes:
  certs:

networks:
  proxy-network-internal:
    external: true
  proxy-network:
    external: true
```
Please note that the `LETSENCRYPT_HOST` disappear.
