### ISSUE TITLE
docker-compose.yml possible with 3rd item?

### ISSUE THREAD

**Issue by srchulo** [nginx-proxy/acme-companion#611]
I'm trying to get `docker-compose.yml` working with my own web server. All of the examples that I can find that have a third service seem to be using `docker-gen`:

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Docker-Compose

I can get https working when I launch all three separately with `docker run` in the examples, but I'd love to get them all working in `docker-compose.yml`. Is this possible? Below is my `docker-compse.yml`:

```yaml
version: "3.7"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./htpasswd:/etc/nginx/htpasswd
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
        ports:
            - "80:80"
            - "443:443"
        restart: always
        network_mode: bridge
    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:rw
        restart: always
        network_mode: bridge
        environment:
            - DEFAULT_EMAIL=user@domain.com
            - NGINX_PROXY_CONTAINER=nginx-proxy
        depends_on:
            - nginx-proxy
    my-app:
        build: .
        volumes:
            - .:/app
        expose:
            - "3000"
        restart: always
        network_mode: bridge
        environment:
            - VIRTUAL_HOST=example.domain.com
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=example.domain.com
        depends_on:
            - nginx-proxy
volumes:
    conf:
    vhost:
    html:
    dhparam:
    certs:
```
