### ISSUE TITLE
ACME_PREFERRED_CHAIN does not honor settings

### ISSUE THREAD

**Issue by maanloper** [nginx-proxy/acme-companion#782]
I seem to be unable to get ACME_PREFERRED_CHAIN to use "ISRG Root X1" instead of "DST Root CA X3"; after countless tries I have not been able to get it to work, hopefully someone can help me find out the issue (either my setup or something related to acme-companion).

I found https://github.com/nginx-proxy/acme-companion/issues/695 and have the same issue while using the most recent ACME-COMPANION version (2.1.0.1), which fixed the problem for the people having the issue for older versions. That makes me think it is not the same issue. Probably the bag-of-water between the screen and chair is the problem :)

My compose file:
```
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy
      - backend
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /home/locki/server/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    networks:
      - proxy
    restart: always

  acme-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: acme-companion
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro`
    `environment:
      - DHPARAM_BITS=4096
    networks:
      - proxy
    restart: always
      
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    environment:
      - VIRTUAL_HOST=www.example.org,www.example.org
      - LETSENCRYPT_HOST=www.example.org,www.example.org
      - ACME_OCSP=true
      - LETSENCRYPT_KEYSIZE=ec-384
      - ACME_PREFERRED_CHAIN="ISRG Root X1"
    networks:
      - backend
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  proxy:
  backend:
```

(Running on Ubuntu 20.04 LTS and using latest Docker and Docker Compose.)

If I go to `/var/lib/docker/volumes/server_acme/_data/default/www.example.org_ecc` and run `openssl x509 -in ca.cer -text -noout` I get:
``` Version: 3 (0x2)
        Serial Number:
            40:01:75:04:83:14:a4:c8:21:8c:84:a9:0c:16:cd:df
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3
        Validity
            Not Before: Oct  7 19:21:40 2020 GMT
            Not After : Sep 29 19:21:40 2021 GMT
        Subject: C = US, O = Let's Encrypt, CN = R3
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
```

confirming ACME-COMPANION does not issue a certificate using "ISRG Root X1".

The only indication on an error I get is either:
`acme-companion    | /app/letsencrypt_service_data: line 9: LE: command not found`
or
`acme-companion    | /app/letsencrypt_service_data: line 9: Root: command not found`

If I look at line 9 of that file on github (letsencrypt_service_data.tmpl), the code at that line is simply `{{end}}`; unlikely that that would be the problem...

What am I doing wrong? If any additional information is required; I can provide it. 
Thanks for any help, even pointers to where I can look further to fix the problem are much appreciated!

**EDIT:**
After some further digging, I used shell to get into the docker container.
```sudo docker exec -it container-name sh```
updated the container and added nano:
```apk update && apk add nano```
to read the `letsencrypt_service_data` file, which looks very different from the one on github, I guess the code is compiled using GOLANG. Content of that file:
```
LETSENCRYPT_CONTAINERS=(
                        '78bae47dfdd5'
)
LETSENCRYPT_78bae47dfdd5_HOST=('www.example.org' 'example.org' )
LETSENCRYPT_78bae47dfdd5_KEYSIZE="ec-384"
LETSENCRYPT_78bae47dfdd5_TEST="<no value>"
LETSENCRYPT_78bae47dfdd5_EMAIL="<no value>"
ACME_78bae47dfdd5_CA_URI="<no value>"
ACME_78bae47dfdd5_PREFERRED_CHAIN=""ISRG Root X1""
ACME_78bae47dfdd5_OCSP="true"
ACME_78bae47dfdd5_EAB_KID="<no value>"
ACME_78bae47dfdd5_EAB_HMAC_KEY="<no value>"
ZEROSSL_78bae47dfdd5_API_KEY="<no value>"
LETSENCRYPT_78bae47dfdd5_RESTART_CONTAINER="<no value>"
```
The value of PREFERRED_CHAIN is in double quotes, whereas the rest is not in double quotes. In https://github.com/nginx-proxy/acme-companion/issues/695 the final solution worked with the environment variable in docker-compose with quotes around it and I copied that example. No matter if I start my container with `ACME_PREFERRED_CHAIN="ISRG Root X1"` or `ACME_PREFERRED_CHAIN=ISRG Root X1`, the result is the same.
What (subtle) mistake am I making?

**Bonus question:**
When Let's Encrypt opens up "ISRG Root X2" (using ECC for the root certs) to the public, can I just change X1 to X2 in the environment variable, or does ACME-COMPANION have to support that first?
