### ISSUE TITLE
 Domain name does not end with a valid public suffix (TLD)"

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nginx-proxy/acme-companion#791]
Bug description
-----------------

The `*_HOST` enviroment variables are not correctly parsed thus resulting in the ending of `\"` instead of `.tld`. My domain name is `jellyfin.pi.tld`. See the logs:

```
 Cannot issue for \"jellyfin.pi.tld\": Domain name does not end with a valid public suffix (TLD)",
```

My docker-compose file:

```yml
version: "3.8"
services:
    nginx-proxy:
      image: nginxproxy/nginx-proxy
      container_name: proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /home/pi/nginx/certs:/etc/nginx/certs
        - /home/pi/nginx/vhost:/etc/nginx/vhost.d
        - /home/pi/nginx/html:/usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx-proxy-acme:
      image: nginxproxy/acme-companion
      depends_on:
        - nginx-proxy
      environment:
        - DEFAULT_EMAIL=francesco.zuppichini@gmail.com
        - NGINX_PROXY_CONTAINER=proxy
      volumes:
        - /home/pi/nginx/certs:/etc/nginx/certs
        - /home/pi/nginx/vhost:/etc/nginx/vhost.d
        - /home/pi/nginx/html:/usr/share/nginx/html
        - /home/pi/acme:/etc/acme.sh
        - /var/run/docker.sock:/var/run/docker.sock:ro
    jellyfin:
        # doc https://hub.docker.com/r/linuxserver/jellyfin
        image: linuxserver/jellyfin
        container_name: jellyfin
        depends_on:
          - nginx-proxy-acme
        environment:
          - PUID=0
          - PGID=0
          - TZ=Europe/Zurich
          - UMASK_SET=022 #optional
          - VIRTUAL_HOST=jellyfin.pi.tld
          - LETSENCRYPT_HOST=jellyfin.pi.tld
          - VIRTUAL_PORT=8096
        volumes:
          - /mnt/cloud/jellyfin/:/config
          - /mnt/cloud/shared/tvseries:/data/tvshows
          - /mnt/cloud/shared/movies/:/data/movies
          - /mnt/cloud/shared/books/:/data/books
          # add hardware acceleration
          # https://jellyfin.org/docs/general/administration/hardware-acceleration.html
          # and https://www.reddit.com/r/jellyfin/comments/ei6ew6/rpi4_hardware_acceleration_guide/
          - /dev/shm:/config/data/transcoding-temp/transcodes
          - /opt/vc/lib:/opt/vc/lib   ## OpenMax Libraries
        ports:
          - 8096:8096
          - 8920:8920 #optional

        restart: unless-stopped
```
acme-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```
v2.1.0-8-g8837acf
```

If this first log line isn't present you are using a v1 image: please provide the tagged version you are using. If you are not using a tagged version latest, please try again with a tagged release before opening an issue (the last v1 tagged release is v1.13.1).

nginx-proxy configuration
-----------------

Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that please provide the full configurations and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

Please provide the logs of:
- your acme-companion container
- your nginx-proxy container (or nginx and docker-gen container in a three containers setup)

```
Creating/renewal jellyfin.pi.tld certificates... (jellyfin.pi.tld)
[Thu May  6 18:11:22 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu May  6 18:11:23 UTC 2021] Creating domain key
[Thu May  6 18:11:40 UTC 2021] The domain key is here: /etc/acme.sh/francesco.zuppichini@gmail.com/jellyfin.pi.tld/jellyfin.pi.tld.key
[Thu May  6 18:11:40 UTC 2021] Single domain='jellyfin.pi.tld'
[Thu May  6 18:11:40 UTC 2021] Getting domain auth token for each domain
[Thu May  6 18:11:42 UTC 2021] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"jellyfin.pi.tld\": Domain name does not end with a valid public suffix (TLD)",
  "status": 400
}```

Docker host
-----------------

 - OS: Raspbian
 - Docker version: 19.03.12
