### ISSUE TITLE
“jrcs/letsencrypt-nginx-proxy-companion” docker image: too many certificates already issued for exact set of domains

### ISSUE THREAD

**Issue by abhimal** [nginx-proxy/acme-companion#793]
I'm using "jwilder/nginx-proxy" y "jrcs/letsencrypt-nginx-proxy-companion" images to create the ssl certificates automatically, when the server its updated and I run "docker-compose down" and "docker-compose up -d" the following error appears

```
[Sat May  8 09:11:04 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
nginx-proxy-letsencrypt_1  | [Sat May  8 09:11:04 UTC 2021] Creating domain key
nginx-proxy-letsencrypt_1  | [Sat May  8 09:11:04 UTC 2021] The domain key is here: /etc/acme.sh/biznageofficial@gmail.com/biznage.com/biznage.com.key
nginx-proxy-letsencrypt_1  | [Sat May  8 09:11:04 UTC 2021] Single domain='biznage.com'
nginx-proxy-letsencrypt_1  | [Sat May  8 09:11:04 UTC 2021] Getting domain auth token for each domain
nginx-proxy-letsencrypt_1  | [Sat May  8 09:11:07 UTC 2021] Create new order error. Le_OrderFinalize not found. {
nginx-proxy-letsencrypt_1  |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx-proxy-letsencrypt_1  |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: biznage.com: see https://letsencrypt.org/docs/rate-limits/",
nginx-proxy-letsencrypt_1  |   "status": 429
nginx-proxy-letsencrypt_1  | }
```

I understand that letsencrypt allows a limited amount of certificates creation over a week. Every time that I have to do a "docker-compose down" and "docker-compose up -d" I'm using one of this instances to generate a certificate. Now I have reached the limit and can't use the site.

Which is the way to avoid certificates generating if is not necessary? Is there a way of reset the counter of this week to keep using the site?

My docker-compose.yml

```
version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - redis
  celery:
    build: ./app
    command: celery -A Backend worker -l INFO
    env_file:
      - .env.prod
    depends_on:
      - web
      - redis
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy
  redis:
    image: redis:5-alpine

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
```

**Comment by edemirkan** [comment]
Hey @abhimal, the latest version of the `acme-companion` (previously `letsencrypt-nginx-proxy-companion`) requires `acme` folder to be mounted for persistence. So your config should be;
```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
```

Here's another sample config which uses this;
https://github.com/edemirkan/rpi-nextcloud/blob/ee043fc5c5f7493ca1d77076d2032c4f624ae90d/docker-compose.yml
