### ISSUE TITLE
Only first N (=18) containers get certs

### ISSUE THREAD

**Issue by mooomooo** [nginx-proxy/acme-companion#832]
Bug description
-----------------

It seems that only the alphabetically first 18 containers have their certs requested / renewed.  

I have many containers running, all started through docker-compose in a bunch of docker-compose files combined with `-f` in the docker-compose command line.  No matter how I change my service names, exactly the first 18 alphabetical containers get handled.  E.g. if I add a new service `a*`, it'll get a cert, but then service `s*` won't get renewed anymore, unless I remove `a*` and then it's back.  And a new service `z*` will never get a cert in the first place.

acme-companion image version
-----------------

```
Info: running acme-companion version v2.1.0-10-gcd3b51b
```

nginx-proxy configuration
-----------------

```
version: '2.2'

services:

  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=${DOMAIN}
    volumes:
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-dhparam:/etc/nginx/dhparam
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-conf:/etc/nginx/conf.d
      - ./conf/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - proxy

  proxy-le:
    image: nginxproxy/acme-companion
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - proxy-certs:/etc/nginx/certs
      - proxy-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - proxy

volumes:
  proxy-conf:
  proxy-vhost:
  proxy-html:
  proxy-dhparam:
  proxy-acme:
  proxy-certs:
     driver_opts:
         type: none
         o: bind
         device: ./certs
```

Docker host
-----------------

 - OS: Ubuntu 20.04.1 LTS
 - Docker version: 19.03.13
