### ISSUE TITLE
Unexpected Certificate Information

### ISSUE THREAD

**Issue by ansidev** [nginx-proxy/acme-companion#836]
Bug description
-----------------
Problem: Invalid certficate.

Check result from: https://www.geocerts.com/ssl-checker

```
Common Name: letsencrypt-nginx-proxy-companion
Issuing CA: letsencrypt-nginx-proxy-companion
```
```
Certificate Common Name (CN) and Hostname Match?
The hostname ({hostname}) does NOT match the Common Name in the certificate (letsencrypt-nginx-proxy-companion). This certificate is currently invalid for this host.
```
```	
Certificate Chain Complete?
A valid Root CA Certificate could not be located, the certificate will likely display browser warnings.

Common Name:letsencrypt-nginx-proxy-companion
Organization:
Valid: July 14, 2021 to July 14, 2022
Issuer: letsencrypt-nginx-proxy-companion
```
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```
Info: running acme-companion version 2.1
```

nginx-proxy configuration
-----------------
```yaml
version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - prod

  acme-companion:
    image: nginxproxy/acme-companion:2.1
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - prod

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  prod:
    driver: bridge
```
Containers logs
-----------------

- Certificate was generated successfully.

Docker host
-----------------

 - OS: Ubuntu 20.04.2
 - Docker version:
 ```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
