### ISSUE TITLE
Missing proxy_pass for default.conf

### ISSUE THREAD

**Issue by yousoff92** [nginx-proxy/acme-companion#837]
I'm not able to access my Angular/NestJs application via nginx-proxy and acme-companion via port 443. It returns status code 500. I've check the default.conf and somehow nginx have return 500. 

```nginx
server {
        server_name api.myname.net;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        return 500;
        ssl_certificate /etc/nginx/certs/default.crt;
        ssl_certificate_key /etc/nginx/certs/default.key;
}

```
I expect it to have proxy pass like this. I can access my app if I modify default.conf it to below

```nginx
server {
	server_name api.myname.net;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
#	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;

	location / {
		proxy_pass http://api.myname.net-upstream;
	}

}
```
Is there any other configuration needed so that i can access my app via the server name port 443 ? without manually change the default.conf.

I'm using docker-compose to create my containers. Here are the portion of my docker-compose [Edited: added backend container]

```yaml
myname-nginx:
    container_name: myname-nginx
    image: jwilder/nginx-proxy:alpine
    ports:
        - 80:80
        - 443:443
    networks:
        - myname-home-network
    volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ../config/ssl/certs:/etc/nginx/certs
        - ../config/ssl/vhost:/etc/nginx/vhost.d
        - ../config/ssl/html:/usr/share/nginx/html
myname-nginx-letsencrypt:
    container_name: myname-nginx-letsencrypt
    image: nginxproxy/acme-companion
    networks:
        - myname-home-network
    volumes_from: 
        - myname-nginx
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ../config/acme/acme:/etc/acme.sh
    environment: 
        - DEFAULT_EMAIL=mail@yourdomain.tld
    depends_on:
        - myname-nginx  


myname-home-backend:
    container_name: myname-home-backend
    image: myname-home-backend:1.0.0
    build:
        context: ../home-app-backend-v2
        target: myname-home-backend-production
        dockerfile: ../home-app-backend-v2/Dockerfile
    command: npm run start:prod    
    environment: 
        - MONGO_DB_URL=mongodb://myname-home-mongodb:27017/myname-app-db-prod
        - NODE_ENV=prod
        - VIRTUAL_HOST=api.myname.net
        - VIRTUAL_PORT=3000
        - LETSENCRYPT_HOST=api.myname.net
        - LETSENCRYPT_EMAIL=mail@yourdomain.tld
    ports:
        - 3000:3000
        - 9229:9229
    networks:
        - myname-home-network
    volumes:
        - ../log/backend:/usr/src/app/log
    depends_on:
        - myname-home-redis
        - myname-home-mongodb
        - myname-nginx-letsencrypt

myname-home-frontend:
    container_name: myname-home-frontend
    image: myname-home-frontend:1.0.0
    environment: 
        - VIRTUAL_HOST=home.myname.net
        - VIRTUAL_PORT=4200
    build:
        context: ../home-app-frontend
        target: myname-home-frontend-production
        dockerfile: ../home-app-frontend/Dockerfile
    ports:
        - 4200:4200
    networks:
        - myname-home-network
    depends_on:
        - myname-home-backend    
```

Versions :
nginx = 1.21.1
docker = 20.10.7, build f0df350
docker-compose = 1.29.2, build 5becea4c
host OS = PopOS 20.04
