### ISSUE TITLE
sharing html volume between website container, nginx-proxy and acme-companion

### ISSUE THREAD

**Issue by TimKraemer** [nginx-proxy/acme-companion#859]
Hi,

sorry about this basic question, but reading the docs and fiddling around for a few days and I'm still stuck:

I do have a running nginx-proxy, my website is reachable over http and displays the correct content:
`curl http://my.correct.url`  <- this works! 

however, when I'm trying to add acme-companion it can't access it's .well-known acme-secret:
```bash
response='{"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Invalid response from http://my.correct.url/.well-known/acme-challenge/BjGpifuu64dNmIASjWyZ0xzG3ngm-JcLLmVgtgeL9AY [xxx.xxx.xxx.xxx]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003enginx/1.21.0\u003c/ce\"","status": 403},"url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/27460844030/xVldLw","token":"BjGpifuu64dNmIASjWyZ0xzG3ngm-JcLLmVgtgeL9AY","validationRecord":[{"url":"http://my.correct.url/.well-known/acme-challenge/BjGpifuu64dNmIASjWyZ0xzG3ngm-JcLLmVgtgeL9AY","hostname":"my.correct.url","port":"80","addressesResolved":["xxx.xxx.xxx.xxx"],"addressUsed":"xxx.xxx.xxx.xxx"}],"validated":"2021-09-02T22:44:48Z"}'
```
* I replaced my ip and url - but I checked, they are correct

then I tried debugging, so I connected to my **acme-companion** container and tried writing hello-world
```bash
docker exec acme-companion bash -c 'echo "Hello world!" > /usr/share/nginx/html/.well-known/acme-challenge/hello-world'
```
but I can't access it via my domain:
`curl http://my.correct.url/.well-known/acme-challenge/hello-world` -> 404

on further research I found out, that if I bash into my acme-companion, it indeed has a hello-world file in `/usr/share/nginx/html/.well-known/acme-challenge`, nginx-proxy has it also (as expected).
And all that makes perfect sense to me, because **how should nginx-proxy know, that this specific file should be served from there instead of from `my-website` container?**

I'm sure I'm missing an essential step, but which?

here's my docker-compose.yml:
```yml
version: "3.9"

networks:
    internal:
    external:

services:
  my-website:
    container_name: my-website
    ports:
      - '8001:80'
    volumes:
      - '/home/tim/website/:/usr/share/nginx/html'  # this it where my html files are on host
    image: nginx
    restart: always
    depends_on:
      - nginx-proxy
    networks:
      - external
    environment:
      - VIRTUAL_HOST=my.correct.url
      - LETSENCRYPT_HOST=my.correct.url
      - LETSENCRYPT_EMAIL=my@email.adress
      
  nginx-proxy:
     image: nginxproxy/nginx-proxy:alpine
     container_name: nginx-proxy
     restart: always
     ports:
       - "80:80"
       - "443:443"
     environment:
       - ENABLE_IPV6=true
       - DHPARAM_GENERATION=false
     volumes:
       - "/var/run/docker.sock:/tmp/docker.sock:ro"
       - "certs:/etc/nginx/certs:ro"
       - "html:/usr/share/nginx/html"
       - "vhosts:/etc/nginx/vhost.d:ro"
     networks:
       - external
     labels:
       - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  acme-companion:
     container_name: acme-companion
     restart: always
     image: nginxproxy/acme-companion:latest
     depends_on:
      - nginx-proxy
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock:ro"
       - "certs:/etc/nginx/certs:rw"
       - "vhosts:/etc/nginx/vhost.d:rw"
       - "html:/usr/share/nginx/html:rw"
       - "acme:/etc/acme.sh"
     environment:
       - DEBUG=1

volumes:
   certs:
   acme:
   html:
   vhosts:
```
