### ISSUE TITLE
Verify domain file not found

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [nginx-proxy/acme-companion#867]
![image](https://user-images.githubusercontent.com/9791364/133362626-1ee3f4fa-8c3f-4b89-a7cc-395d23046b83.png)

docker nginx

```
version: '2'

services:
   nginx-proxy:
     container_name: 'nginx-proxy'
     image: nginx
     ports: 
       - "80:80"
       - 443:443
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - vhost:/etc/nginx/vhost.d
       - html:/usr/share/nginx/html
       - certs:/etc/nginx/certs:ro
       - /var/run/docker.sock:/tmp/docker.sock:ro
     networks:
       - application
     labels:
       - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
         
   nginx-letsencrypt:
      container_name: 'nginx-proxy-letsencrypt'
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      depends_on:
        - nginx-proxy
      volumes_from:
        - nginx-proxy
      environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - application
      labels:
       - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
volumes:
  conf:
  vhost:
  html:
  certs:
  
networks:
  application:
    external: true
```
nginx.conf
![image](https://user-images.githubusercontent.com/9791364/133362797-9585fd07-7399-4bfc-9628-609465c6fce1.png)

docker domain
![image](https://user-images.githubusercontent.com/9791364/133362857-1912519b-d52d-49c4-9172-ee9f83521e89.png)
