### ISSUE TITLE
Error: can't get docker-gen container id

### ISSUE THREAD

**Issue by susiq** [nginx-proxy/acme-companion#889]
Bug description
i seem not to get certification and the container for : jrcs/letsencrypt-nginx-proxy-companion is not running the site itself seem to work but without getting the certification 

-----------------
docker-compose 

```yaml
version: "3.3"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
      - 443:443
    volumes:
      - static-data:/vol/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=${Email_lets}
      - NGINX_PROXY_CONTAINER=${Proxy_container}
 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx
      - acme:/etc/acme.sh
    depends_on:
      - proxy

volumes:
  postgres-data:
  static-data:
  certs:
  html:
  vhost:
  acme:
```

docker file for proxy sever :  

```dockerfile
FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="david"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./run.sh /run.sh

ENV LISTEN_PORT=8000
ENV APP_HOST=app
ENV APP_PORT=9000

USER root

RUN mkdir -p /vol/static && \
    chmod 755 /vol/static && \
    touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf && \
    chmod +x /run.sh

VOLUME /vol/static


CMD ["/run.sh"]
```

nginx configuration :

# configuration of the server
server {
    # the port your site will be served on

    listen      ${LISTEN_PORT};
    charset     utf-8;

    # max upload size
    client_max_body_size 10M;   # adjust to taste

    location /static {
        alias /vol/static;
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass   ${APP_HOST}:${APP_PORT};
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size    10M;
        include     /etc/nginx/uwsgi_params; # the uwsgi_params file you installed
    }
}

the error log is 
```console
attaching to simple_ssl_uwsgi_db_1, simple_ssl_uwsgi_app_1, simple_ssl_uwsgi_proxy_1, simple_ssl_uwsgi_nginx-proxy-letsencrypt_1
app_1                      | total 12
app_1                      | drwxr-xr-x    3 simple_a simple_a      4096 Nov  4 09:32 .
app_1                      | drwxr-xr-x    1 root     root          4096 Nov  4 09:32 ..
app_1                      | drwxr-xr-x    4 simple_a simple_a      4096 Nov  3 10:06 web
app_1                      | total 16
app_1                      | drwxr-xr-x    4 simple_a simple_a      4096 Nov  3 10:06 .
app_1                      | drwxr-xr-x    3 simple_a simple_a      4096 Nov  4 09:32 ..
app_1                      | drwxr-xr-x    2 simple_a simple_a      4096 Nov  3 10:06 media
app_1                      | drwxr-xr-x    8 simple_a simple_a      4096 Nov  3 10:06 static
app_1                      | root
app_1                      | Waiting for database...
app_1                      | Database available!
app_1                      | 
app_1                      | 0 static files copied to '/vol/web/static', 217 unmodified.
db_1                       | 
db_1                       | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1                       | 
db_1                       | 2021-11-04 12:31:17.555 UTC [1] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
db_1                       | 2021-11-04 12:31:17.561 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                       | 2021-11-04 12:31:17.561 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1                       | 2021-11-04 12:31:17.567 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                       | 2021-11-04 12:31:17.576 UTC [23] LOG:  database system was interrupted; last known up at 2021-11-04 12:28:28 UTC
db_1                       | 2021-11-04 12:31:17.613 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
db_1                       | 2021-11-04 12:31:17.618 UTC [23] LOG:  redo starts at 0/1636E48
db_1                       | 2021-11-04 12:31:17.618 UTC [23] LOG:  invalid record length at 0/1636E80: wanted 24, got 0
db_1                       | 2021-11-04 12:31:17.618 UTC [23] LOG:  redo done at 0/1636E48
db_1                       | 2021-11-04 12:31:17.647 UTC [1] LOG:  database system is ready to accept connections
nginx-proxy-letsencrypt_1  | Info: running acme-companion version v2.1.0-28-g1785bc5
proxy_1                    | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
proxy_1                    | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: using the "epoll" event method
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: nginx/1.21.1
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: built by gcc 8.3.0 (Debian 8.3.0-6) 
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: OS: Linux 5.11.0-1020-aws
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: getrlimit(RLIMIT_NOFILE): 1048576:1048576
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: start worker processes
proxy_1                    | 2021/11/04 12:31:19 [notice] 22#22: start worker process 23
nginx-proxy-letsencrypt_1  | jq: error (at <stdin>:1): Cannot iterate over null (null)
nginx-proxy-letsencrypt_1  | Error: can't get docker-gen container id !
nginx-proxy-letsencrypt_1  | If you are running a three containers setup, check that you are doing one of the following :
nginx-proxy-letsencrypt_1  | 	- Set the NGINX_DOCKER_GEN_CONTAINER env var on the letsencrypt-companion container to the name of the docker-gen container.
nginx-proxy-letsencrypt_1  | 	- Label the docker-gen container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'.
simple_ssl_uwsgi_nginx-proxy-letsencrypt_1 exited with code 1
```

thnak you 

-----------------

. Ubuntu 20.04
 - Docker version: 3.3
