### ISSUE TITLE
Nginx doesn't serve acme verification files (22: Invalid argument)

### ISSUE THREAD

**Issue by jypma** [nginx-proxy/acme-companion#954]
Bug description
-----------------

My setup (docker-compose with 2 containers) has been working well for years, but suddenly wasn't refreshing certificates. Upgrading to latest made no difference. The symptom is that nginx isn't serving up the ACME challenge, even though the companion container is writing them into its `html` directory. Nginx sends a 200 OK, but no response body.

```
curl -v http://XXX/.well-known/acme-challenge/nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc
*   Trying YYY:80...
* Connected to XXX (YYY) port 80 (#0)
> GET /.well-known/acme-challenge/nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc HTTP/1.1
> Host: XXX
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Fri, 22 Apr 2022 11:44:25 GMT
< Content-Type: application/octet-stream
< Content-Length: 87
< Last-Modified: Fri, 22 Apr 2022 11:30:35 GMT
< Connection: keep-alive
< ETag: "626291db-57"
< Accept-Ranges: bytes
<
* transfer closed with 87 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 87 bytes remaining to read
```

The relevant log line of the `nginx` container:

```
nginx.1     | XXX 192.168.0.1 - - [22/Apr/2022:11:48:50 +0000] "GET /.well-known/acme-challenge/nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc HTTP/1.1" 200 0 "-" "curl/7.82.0" "-"
nginx.1     | 2022/04/22 11:48:50 [alert] 175#175: *186 sendfile() failed (22: Invalid argument) while sending response to client, client: 192.168.0.1, server: XXX, request: "GET /.well-known/acme-challenge/nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc HTTP/1.1", host: "XXX"
```

The files themselves are in the `html` directory just fine:

```
jan@zzzzz:~ $ docker exec -ti nextcloud-nginx-proxy-1 /bin/bash
root@3e8821da79d8:/app# cat /usr/share/nginx/html/.well-known/acme-challenge/nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc
nm1XE_6W_TPLe8Wl1JbPGZ48XR1h749lqkl6C1yDmxc.H-19kDCVpj[...snip...]:/app#
```

When making the manual `curl` above, the `acme-companion` container doesn't log. However, when actually trying to refresh certificates, it logs a similar message as the manual `curl`.

I'm on arch linux, kernel 5.16.12-arch1-1. Here's the relevant containers and versions from my docker-compose file:
```yaml
version: '2'

services:
  postgresql:
[...snipped...]

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0.1
    network_mode: bridge
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: nginxproxy/acme-companion:2.2.1
    restart: always
    network_mode: bridge
    environment:
      DEBUG: "1"
      DEFAULT_EMAIL: "jan[...snip...]"
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextcloud:
[...snipped...]

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
```

I'm running on zfs, in case that makes a difference. As said, this has worked fine until probably about a few months ago (`now()` minus letsencrypt certificate lifetime :-) )
