### ISSUE TITLE
Better starting flow with default certificate

### ISSUE THREAD

**Issue by azlux** [nginx-proxy/acme-companion#956]
(Bug)? description
-----------------

During the start, the default certificate is present for all domains (certificate named "letsencrypt-nginx-proxy-companion")

I currently have around 30 domains, it's take time, so I receive alerts saying my domain isn't good on my monitoring tool, nextcloud clients, smartphone....
Is that possible to say to the acme-companion to start with existing certificate without verify them one by one. Or making an improvement to do it ?
The script can check them in a second step.

I suppose I can "avoid" the issue on the main domain with a mount point to have a file at `/etc/nginx/certs/default.cr` : 
https://github.com/nginx-proxy/acme-companion/blob/main/app/entrypoint.sh#L110-L117
But I don't think it's enough.

What's your advice ?

docker image version : 1a7f5b3bc6cf
acme-companion version : v2.2.1

-----------------

nginx-proxy's Docker configuration

<details>
  <summary>Click to expand!</summary>

```
    nginx:
        image: nginxproxy/nginx-proxy
        container_name: nginx
        hostname: nginx
        restart: on-failure
        ports:
            - "80:80"
            - "443:443"
        environment:
            ENABLE_IPV6: "true"
            TZ: "Europe/*****"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ../data/nginx/certs:/etc/nginx/certs:ro
            - ../data/nginx/conf.d:/etc/nginx/conf.d
            - ../data/nginx/htpasswd:/etc/nginx/htpasswd
            - ../data/nginx/vhost.d:/etc/nginx/vhost.d
            - ../data/nginx/dhparam:/etc/nginx/dhparam
            - ../data/nginx/logs:/var/log/nginx
            - ../data/nginx/html:/usr/share/nginx/html
        networks:
            default:
                ipv4_address: 172.18.0.100

    letsencrypt:
        image: nginxproxy/acme-companion
        container_name: letsencrypt
        hostname: letsencrypt
        environment:
            DEFAULT_EMAIL: ********
            NGINX_PROXY_CONTAINER: nginx
        volumes_from:
            - nginx
        volumes:
            - ../data/nginx/certs:/etc/nginx/certs:rw
            - ../data/letsencrypt/acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - nginx
```
</details>

Containers logs
-----------------

<details>
  <summary>Click to expand!</summary>

```
letsencrypt         | Info: running acme-companion version v2.2.1
letsencrypt         | Info: A custom dhparam.pem file was provided. Best practice is to use standardized RFC7919 Diffie-Hellman groups instead.
letsencrypt         | Reloading nginx proxy (nginx)...
letsencrypt         | 2022/04/25 16:30:14 Generated '/etc/nginx/conf.d/default.conf' from 47 containers
letsencrypt         | Warning: /app/letsencrypt_service_data not found, skipping data from containers.
letsencrypt         | 2022/04/25 14:30:19 Generated '/app/letsencrypt_service_data' from 47 containers
letsencrypt         | 2022/04/25 14:30:19 Running '/app/signal_le_service'
letsencrypt         | 2022/04/25 14:30:19 Watching docker events
letsencrypt         | 2022/04/25 14:30:19 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt         | Reloading nginx proxy (nginx)...
letsencrypt         | 2022/04/25 16:30:20 Generated '/etc/nginx/conf.d/default.conf' from 47 containers
letsencrypt         | Reloading nginx proxy (nginx)...
letsencrypt         | 2022/04/25 16:30:20 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
letsencrypt         | Creating/renewal azlux.fr certificates... (azlux.fr z.azlux.fr)
letsencrypt         | [Mon Apr 25 14:30:28 UTC 2022] Domains not changed.
letsencrypt         | [Mon Apr 25 14:30:28 UTC 2022] Skip, Next renewal time is: Thu May 26 16:09:38 UTC 2022
letsencrypt         | [Mon Apr 25 14:30:28 UTC 2022] Add '--force' to force to renew.
letsencrypt         | Creating/renewal a.azlux.fr certificates... (a.azlux.fr)
letsencrypt         | [Mon Apr 25 14:30:29 UTC 2022] Domains not changed.
letsencrypt         | [Mon Apr 25 14:30:29 UTC 2022] Skip, Next renewal time is: Thu May 26 16:10:00 UTC 2022
letsencrypt         | [Mon Apr 25 14:30:29 UTC 2022] Add '--force' to force to renew.
letsencrypt         | [Mon Apr 25 14:30:29 UTC 2022] Add '--force' to force to renew.
letsencrypt         | Reloading nginx proxy (nginx)...
letsencrypt         | 2022/04/25 16:30:30 Generated '/etc/nginx/conf.d/default.conf' from 47 containers
letsencrypt         | Creating/renewal b.azlux.fr certificates... (b.azlux.fr)
letsencrypt         | [Mon Apr 25 14:30:33 UTC 2022] Domains not changed.
letsencrypt         | [Mon Apr 25 14:30:33 UTC 2022] Skip, Next renewal time is: Thu May 26 16:10:16 UTC 2022
letsencrypt         | [Mon Apr 25 14:30:33 UTC 2022] Add '--force' to force to renew.
letsencrypt         | Reloading nginx proxy (nginx)...
letsencrypt         | 2022/04/25 16:30:33 Generated '/etc/nginx/conf.d/default.conf' from 47 containers
letsencrypt         | Creating/renewal c.azlux.fr certificates... (c.azlux.fr)
letsencrypt         | [Mon Apr 25 14:30:34 UTC 2022] Domains not changed.
letsencrypt         | [Mon Apr 25 14:30:34 UTC 2022] Skip, Next renewal time is: Thu May 26 16:10:34 UTC 2022
letsencrypt         | [Mon Apr 25 14:30:34 UTC 2022] Add '--force' to force to renew.
letsencrypt         | Creating/renewal d.azlux.fr certificates... (d.azlux.fr)
letsencrypt         | [Mon Apr 25 14:30:37 UTC 2022] Domains not changed.
letsencrypt         | [Mon Apr 25 14:30:37 UTC 2022] Skip, Next renewal time is: Thu May 26 16:10:47 UTC 2022
letsencrypt         | [Mon Apr 25 14:30:37 UTC 2022] Add '--force' to force to renew.
letsencrypt         | Creating/renewal e.azlux.fr certificates... (e.azlux.fr)
letsencrypt         | 2022/04/25 14:30:38 Received event start for container f97316d1521a
[...]
```
</details>

Docker host
-----------------

 - OS: Debian 11.3
 - Docker version: Docker version 20.10.5+dfsg1, build 55c4c88
