### ISSUE TITLE
reloading website from a certain route, causes redirects

### ISSUE THREAD

**Issue by mboon1975** [nginx-proxy/acme-companion#983]
My docker-compose looks like following: 
```
version: "3.9"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=name@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure

  website:
    container_name: website
    image: company/website:latest
    environment:
      VIRTUAL_HOST: domain.company.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: domain.company.com
      LETSENCRYPT_EMAIL: name@gmail.com
    restart: on-failure
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

```
The acme company works just fine, certificates are loaded but when the website is reloaded from domain.company.com/route1 then it results in too many redirects. I've already reviewed the nginx.conf that has been generated, but i don't see the issue. Any help is appreciated.

default.conf: 
```
upstream domain.company.com {
        server 172.18.0.4:80;
}
server {
        server_name domain.company.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        # Do not HTTPS redirect Let'sEncrypt ACME challenge
        location ^~ /.well-known/acme-challenge/ {
                auth_basic off;
                auth_request off;
                allow all;
                root /usr/share/nginx/html;
                try_files $uri =404;
                break;
        }
        location / {
                return 301 https://$host$request_uri;
        }
}
server {
        server_name domain.company.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/domain.company.com.crt;
        ssl_certificate_key /etc/nginx/certs/domain.company.com.key;
        ssl_dhparam /etc/nginx/certs/domain.company.com.dhparam.pem;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/certs/domain.company.com.chain.pem;
        add_header Strict-Transport-Security "max-age=31536000" always;
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://domain.company.com;
}
}

```
